version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-ppassword"]
        timeout: 20s
        retries: 10
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"

volumes:
  mysql:
